# Generated by Django 3.2.25 on 2024-11-26 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='platform1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_platform1_set', to='application01.platform'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='platform2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_platform2_set', to='application01.platform'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='platform1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_platform1_set', to='application01.platform'),
        ),
        migrations.AlterField(
            model_name='section',
            name='platform2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_platform2_set', to='application01.platform'),
        ),
        migrations.AlterUniqueTogether(
            name='transfer',
            unique_together={('platform1', 'platform2')},
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='platforms_1',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='platforms_2',
        ),
    ]
