# Generated by Django 3.2.25 on 2024-11-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application01', '0002_auto_20241126_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='colour',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
