# Generated by Django 3.2.25 on 2024-11-27 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application01', '0003_line_colour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_type',
            new_name='image_name',
        ),
    ]
