# Generated by Django 3.2.25 on 2024-11-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application01', '0004_rename_image_type_image_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
