# Generated by Django 3.2.25 on 2024-11-27 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application01', '0005_alter_image_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='icon_image',
        ),
    ]
