# Generated by Django 3.2.25 on 2024-12-20 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application01', '0006_remove_line_icon_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exit',
            unique_together={('station', 'exit_no')},
        ),
    ]
